<a href="https://colab.research.google.com/github/mahapara2411/Capstone-2/blob/main/Product_Recommendation%20using%20MBA%20%26%20CF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from datetime import datetime, timedelta
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [ ]:
df = pd.read_excel("Retail_cleaned_dataset.xlsx")

In [ ]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2019-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2019-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2019-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2019-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2019-12-01 07:45:00,1.25,13085,United Kingdom

2. Prepare the Data¶

In [ ]:
df.shape

(779428, 8)

In [ ]:
top_10 = df.groupby('Country').nunique().sort_values('Invoice', ascending=False).head(10)
top_10

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID
Country,,,,,,,
United Kingdom,33536,4619,5249,404,31557,552,5350
Germany,789,2172,2410,57,783,125,107
France,614,2003,2180,102,614,122,95
EIRE,567,2793,3052,81,565,162,5
Netherlands,228,1246,1354,71,228,99,22
Spain,154,1409,1474,43,154,92,41
Belgium,149,989,1080,33,149,78,29
Sweden,104,581,607,50,102,69,19
Australia,95,789,833,55,93,82,15
Portugal,93,907,979,30,93,78,24

In [ ]:
top_10_transaction = pd.DataFrame(df.groupby('Country').nunique().sort_values('Invoice', 
                                                                        ascending=False).head(10)['Invoice'])

In [ ]:
top_10_transaction

                Invoice
Country
United Kingdom    33536
Germany             789
France              614
EIRE                567
Netherlands         228
Spain               154
Belgium             149
Sweden              104
Australia            95
Portugal             93

In [ ]:
#Import plotly.express libraries for visualization
import plotly.express as px

# total bookings per market segment (incl. canceled)
segments=top_10_transaction

# pie plot
fig = px.pie(segments,
             values=top_10_transaction['Invoice'],
             names=top_10_transaction.index,
             title="Country Performance by Number of Invoice",
             template="seaborn")
fig.update_traces(rotation=-90, textinfo="percent+label")
fig.show()

**MBA Using Apriori Algorithm**

In [ ]:
basket_plus = (df[df['Country'] =="United Kingdom"].groupby(['Invoice', 'Description'])['Quantity']
               .sum().unstack().reset_index().fillna(0).set_index('Invoice'))
basket_plus

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
Invoice,,,,,,,,,,,,,,,,,,,,,
489434,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
489435,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
489436,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
489437,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
489438,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581582,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581583,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581584,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,12.0,0.0,0.0,0.0,24.0,0.0,0.0
581586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
basket_plus.tail()

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
Invoice,,,,,,,,,,,,,,,,,,,,,
581582,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581583,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581584,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
581585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,12.0,0.0,0.0,0.0,24.0,0.0,0.0
581586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
def encode_units(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1
    
basket_encode_plus = basket_plus.applymap(encode_units)
basket_encode_plus

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
Invoice,,,,,,,,,,,,,,,,,,,,,
489434,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489435,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489436,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489437,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489438,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581582,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581583,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
basket_encode_plus.tail()

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
Invoice,,,,,,,,,,,,,,,,,,,,,
581582,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581583,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
basket_filter_plus = basket_encode_plus[(basket_encode_plus > 0).sum(axis=1) >= 2]
basket_filter_plus

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
Invoice,,,,,,,,,,,,,,,,,,,,,
489434,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489435,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489436,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489437,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489438,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581582,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581583,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581584,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
581585,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
581586,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
!pip install mlxtend

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.14.0)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.7.3)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.21.6)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.3.5)
Requirement already satisfied: matplotlib>=1.5.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from kiwisolver>=1.0.1->matplotlib>=1.5.1->mlxtend) (4.1.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.1->mlxtend) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=1.5.1->mlxtend) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (3.1.0)

In [ ]:
from mlxtend.frequent_patterns import apriori

In [ ]:
frequent_itemsets_plus = apriori(basket_filter_plus, min_support=0.03, 
                                 use_colnames=True).sort_values('support', ascending=False).reset_index(drop=True)

frequent_itemsets_plus['length'] = frequent_itemsets_plus['itemsets'].apply(lambda x: len(x))

frequent_itemsets_plus

     support                              itemsets  length
0   0.151028  (WHITE HANGING HEART T-LIGHT HOLDER)       1
1   0.091234            (REGENCY CAKESTAND 3 TIER)       1
2   0.080970       (ASSORTED COLOUR BIRD ORNAMENT)       1
3   0.076846             (JUMBO BAG RED RETROSPOT)       1
4   0.062262                       (PARTY BUNTING)       1
..       ...                                   ...     ...
68  0.031115            (JUMBO STORAGE BAG SKULLS)       1
69  0.030758                (LUNCH BAG RED SPOTTY)       1
70  0.030433               (NO SINGING METAL SIGN)       1
71  0.030400    (PINK BLUE FELT CRAFT TRINKET BOX)       1
72  0.030368  (VINTAGE HEADS AND TAILS CARD GAME )       1

[73 rows x 3 columns]

In [ ]:
frequent_itemsets_plus[ (frequent_itemsets_plus['length']  == 2) &
                        (frequent_itemsets_plus['support'] >= 0.03) ]

     support                                           itemsets  length
46  0.035532  (RED HANGING HEART T-LIGHT HOLDER, WHITE HANGI...       2
67  0.031570  (WOODEN FRAME ANTIQUE WHITE , WOODEN PICTURE F...       2

In [ ]:
from mlxtend.frequent_patterns import association_rules

In [ ]:
association_rules(frequent_itemsets_plus, metric='lift', 
                  min_threshold=1).sort_values('lift', ascending=False).reset_index(drop=True)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(WOODEN FRAME ANTIQUE WHITE ),(WOODEN PICTURE FRAME WHITE FINISH),0.055702,0.052129,0.031570,0.566764,10.872332,0.028666,2.187885
1,(WOODEN PICTURE FRAME WHITE FINISH),(WOODEN FRAME ANTIQUE WHITE ),0.052129,0.055702,0.031570,0.605607,10.872332,0.028666,2.394311
2,(WHITE HANGING HEART T-LIGHT HOLDER),(RED HANGING HEART T-LIGHT HOLDER),0.151028,0.050213,0.035532,0.235269,4.685441,0.027949,1.241988
3,(RED HANGING HEART T-LIGHT HOLDER),(WHITE HANGING HEART T-LIGHT HOLDER),0.050213,0.151028,0.035532,0.707633,4.685441,0.027949,2.903785

**Creating a Customer-Item Matrix**

In [ ]:
customer_item_matrix = df.pivot_table(index='CustomerID',columns='StockCode',values='Quantity',aggfunc='sum')

In [ ]:
customer_item_matrix.loc[12481:].head()

StockCode,10002,10080,10109,10120,10125,10133,10134,10135,10138,11001,...,BANK CHARGES,C2,D,DOT,M,PADS,POST,SP1002,TEST001,TEST002
CustomerID,,,,,,,,,,,,,,,,,,,,,
12481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,NaN
12482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
12483,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN
12484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN
12485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
customer_item_matrix.shape

(5878, 4634)

In [ ]:
df['CustomerID'].nunique()

5878

In [ ]:
df['StockCode'].nunique()

4634

In [ ]:
customer_item_matrix.loc[12348.0].sum()

2714.0

**One Hot Encoding: We apply lambda function to convert anything above zero to 1 and zero to 0**

In [ ]:
customer_item_matrix = customer_item_matrix.applymap(lambda x: 1 if x>0 else 0)

In [ ]:
customer_item_matrix.loc[12481:].head()

StockCode,10002,10080,10109,10120,10125,10133,10134,10135,10138,11001,...,BANK CHARGES,C2,D,DOT,M,PADS,POST,SP1002,TEST001,TEST002
CustomerID,,,,,,,,,,,,,,,,,,,,,
12481,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12482,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
12483,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12484,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
12485,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

** User based Collaborative Filtering using Sklearn module**

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
user_to_user_sim_matrix = pd.DataFrame(cosine_similarity(customer_item_matrix))

In [ ]:
user_to_user_sim_matrix.head()

,0,1,2,3,4,5,6,7,8,9,...,5868,5869,5870,5871,5872,5873,5874,5875,5876,5877
0,1.00000,0.000000,0.000000,0.131060,0.000000,0.000000,0.023002,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.070535,0.000000
1,0.00000,1.000000,0.053452,0.045502,0.043214,0.038881,0.031944,0.055728,0.023395,0.090351,...,0.037987,0.0,0.067344,0.064820,0.102869,0.113961,0.067344,0.0,0.076186,0.024398
2,0.00000,0.053452,1.000000,0.017025,0.048507,0.000000,0.023905,0.000000,0.026261,0.067612,...,0.000000,0.0,0.000000,0.000000,0.000000,0.138580,0.000000,0.0,0.000000,0.054772
3,0.13106,0.045502,0.017025,1.000000,0.041292,0.037152,0.152617,0.071000,0.044710,0.057555,...,0.054447,0.0,0.032174,0.020646,0.049147,0.140654,0.016087,0.0,0.062399,0.038854
4,0.00000,0.043214,0.048507,0.041292,1.000000,0.000000,0.028989,0.050572,0.000000,0.000000,...,0.000000,0.0,0.000000,0.058824,0.000000,0.038782,0.000000,0.0,0.029630,0.000000

We setup user to user matrix table column names and the user ID¶

In [ ]:
user_to_user_sim_matrix.columns = customer_item_matrix.index

In [ ]:
user_to_user_sim_matrix['CustomerID'] = customer_item_matrix.index

In [ ]:
user_to_user_sim_matrix = user_to_user_sim_matrix.set_index('CustomerID')

In [ ]:
user_to_user_sim_matrix.head()

CustomerID,12346,12347,12348,12349,12350,12351,12352,12353,12354,12355,...,18278,18279,18280,18281,18282,18283,18284,18285,18286,18287
CustomerID,,,,,,,,,,,,,,,,,,,,,
12346,1.00000,0.000000,0.000000,0.131060,0.000000,0.000000,0.023002,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.070535,0.000000
12347,0.00000,1.000000,0.053452,0.045502,0.043214,0.038881,0.031944,0.055728,0.023395,0.090351,...,0.037987,0.0,0.067344,0.064820,0.102869,0.113961,0.067344,0.0,0.076186,0.024398
12348,0.00000,0.053452,1.000000,0.017025,0.048507,0.000000,0.023905,0.000000,0.026261,0.067612,...,0.000000,0.0,0.000000,0.000000,0.000000,0.138580,0.000000,0.0,0.000000,0.054772
12349,0.13106,0.045502,0.017025,1.000000,0.041292,0.037152,0.152617,0.071000,0.044710,0.057555,...,0.054447,0.0,0.032174,0.020646,0.049147,0.140654,0.016087,0.0,0.062399,0.038854
12350,0.00000,0.043214,0.048507,0.041292,1.000000,0.000000,0.028989,0.050572,0.000000,0.000000,...,0.000000,0.0,0.000000,0.058824,0.000000,0.038782,0.000000,0.0,0.029630,0.000000

In [ ]:
user_to_user_sim_matrix.loc[12350.0].sort_values(ascending = False)

CustomerID
12350    1.000000
12636    0.242536
12568    0.216930
12603    0.171499
12814    0.171499
           ...
14964    0.000000
14967    0.000000
14968    0.000000
14969    0.000000
18287    0.000000
Name: 12350, Length: 5878, dtype: float64

**Items bought by User A**

In [ ]:
user_to_user_sim_matrix.loc[12350.0].sort_values(ascending=False)
items_bought_by_A = customer_item_matrix.loc[12350.0][customer_item_matrix.loc[12350.0]>0]
print("Items Bought by A: ")
print(items_bought_by_A)

Items Bought by A:
StockCode
20615     1
20652     1
21171     1
21832     1
21864     1
21866     1
21908     1
21915     1
22348     1
22412     1
22551     1
22557     1
22620     1
79066K    1
79191C    1
84086C    1
POST      1
Name: 12350, dtype: int64

**Items bought by B**

In [ ]:
items_bought_by_B = customer_item_matrix.loc[17935.0][customer_item_matrix.loc[17935.0]>0]
print("Items bought by B:")
print(items_bought_by_B)

print()

items_to_recommend_to_B = set(items_bought_by_A.index) - set(items_bought_by_B.index)
print("Items to Recommend to B ")
print(items_to_recommend_to_B)
df.loc[df['StockCode'].isin(items_to_recommend_to_B),['StockCode', 'Description']].drop_duplicates().set_index('StockCode')

Items bought by B:
StockCode
20657     1
20659     1
20713     1
20828     1
20856     1
20983     1
21051     1
21866     1
21867     1
21930     1
21931     1
21934     1
22200     1
22202     1
22208     1
22209     1
22210     1
22211     1
22304     1
22305     1
22423     1
22449     1
22450     1
22473     1
22474     1
22475     1
22513     1
22551     1
22553     1
22557     1
22633     1
22640     1
22654     1
22659     1
22697     1
22698     1
22699     1
22749     1
22752     1
22753     1
22754     1
22755     1
22759     1
22834     1
22837     1
22890     1
22906     1
23290     1
23292     1
23309     1
85214     1
47599B    1
48173C    1
75149N    1
82001S    1
85049E    1
85099B    1
85099C    1
85232B    1
POST      1
Name: 17935, dtype: int64

Items to Recommend to B
{'84086C', 20615, 21832, 21864, 20652, 22348, 22412, 21171, 21908, '79066K', '79191C', 21915, 22620}

                               Description
StockCode
21864      UNION JACK FLAG PASSPORT COVER
21908        CHOCOLATE THIS WAY METAL SIGN
21832                 CHOCOLATE CALCULATOR
22348            TEA BAG PLATE RED SPOTTY
79191C         RETRO PLASTIC ELEPHANT TRAY
21171                 BATHROOM METAL SIGN
21915               RED  HARMONICA IN BOX
20652             BLUE SPOTTY LUGGAGE TAG
20615           BLUE SPOTTY PASSPORT COVER
79066K                      RETRO MOD TRAY
84086C             PINK/PURPLE RETRO RADIO
22412      METAL SIGN NEIGHBOURHOOD WITCH
22620          4 TRADITIONAL SPINNING TOPS
20652           BLUE POLKADOT LUGGAGE TAG
22348          TEA BAG PLATE RED RETROSPOT
20615         BLUE POLKADOT PASSPORT COVER

**Item-Based Collaborative Filtering**

In [ ]:
item_item_sim_matrix = pd.DataFrame(cosine_similarity(customer_item_matrix.T))

In [ ]:
item_item_sim_matrix.columns = customer_item_matrix.T.index
item_item_sim_matrix['StockCode'] = customer_item_matrix.T.index
item_item_sim_matrix = item_item_sim_matrix.set_index('StockCode')

In [ ]:
item_item_sim_matrix.head()

StockCode,10002,10080,10109,10120,10125,10133,10134,10135,10138,11001,...,BANK CHARGES,C2,D,DOT,M,PADS,POST,SP1002,TEST001,TEST002
StockCode,,,,,,,,,,,,,,,,,,,,,
10002,1.000000,0.032564,0.0,0.075801,0.100462,0.063130,0.035316,0.076087,0.062609,0.071885,...,0.035829,0.011641,0.0,0.0,0.145514,0.000000,0.085364,0.110432,0.0,0.0
10080,0.032564,1.000000,0.0,0.028916,0.067065,0.033715,0.031435,0.046886,0.000000,0.019195,...,0.000000,0.000000,0.0,0.0,0.059779,0.000000,0.000000,0.000000,0.0,0.0
10109,0.000000,0.000000,1.0,0.000000,0.000000,0.080845,0.000000,0.074953,0.267261,0.000000,...,0.000000,0.000000,0.0,0.0,0.047782,0.000000,0.000000,0.000000,0.0,0.0
10120,0.075801,0.028916,0.0,1.000000,0.059470,0.044845,0.000000,0.051971,0.037062,0.089363,...,0.000000,0.000000,0.0,0.0,0.106018,0.000000,0.013782,0.098058,0.0,0.0
10125,0.100462,0.067065,0.0,0.059470,1.000000,0.060673,0.032325,0.072322,0.000000,0.078957,...,0.024596,0.015982,0.0,0.0,0.102455,0.055364,0.058601,0.075810,0.0,0.0

In [ ]:
top_10_similar_items = list(item_item_sim_matrix.loc[23166].sort_values(ascending=False).iloc[:10].index)

print(top_10_similar_items)
print()
print(df.loc[
    df['StockCode'].isin(top_10_similar_items),
    ['StockCode', 'Description']
].drop_duplicates().set_index('StockCode').loc[top_10_similar_items])

[23166, 23165, 23167, 22993, 23307, 22720, 22722, 23243, 23306, 22961]

                                   Description
StockCode
23166           MEDIUM CERAMIC TOP STORAGE JAR
23165            LARGE CERAMIC TOP STORAGE JAR
23167           SMALL CERAMIC TOP STORAGE JAR
22993             SET OF 4 PANTRY JELLY MOULDS
23307      SET OF 60 PANTRY DESIGN CAKE CASES
22720        SET OF 3 CAKE TINS PANTRY DESIGN
22722        SET OF 6 SPICE TINS PANTRY DESIGN
23243      SET OF TEA COFFEE SUGAR TINS PANTRY
23306          SET OF 36 DOILIES PANTRY DESIGN
23306           SET OF 36 PANTRY PAPER DOILIES
22961                   JAM MAKING SET PRINTED